### ISSUE TITLE
WebApp UI redesign

### ISSUE THREAD

**Issue by jakubklimek** [malyvoj3/csvw-validator#18]
Whe WebApp UI is minimalistic and functional. However, it needs to be further developed to be usable in production.

1. The UI needs to support multilinguality - at least Czech and English strings (in a strings file)
2. The UI needs to include links to the RFC and W3C recommendations, say something about the tool (at least "this is a CSV on the Web validator", etc.)
3. The UI should clearly suggest that the best way of publishing a CSV file is using a URL, along with the JSON-LD descriptor. Therefore, It should first ask for the URL of the descriptor (and maybe the strict mode checkbox with explanation).
4. As a second option, when the user clicks on "I do not have a CSV on the Web descriptor", they should be asked for a CSV file URL.

A completely separate option (tab?) should be upload of both and validation of unpublished CSVs and descriptors.

**Comment by malyvoj3** [comment]
Should be done in new UI from pull request https://github.com/malyvoj3/csvw-validator/pull/27
