### ISSUE TITLE
Cannot install 

### ISSUE THREAD

**Issue by jakubklimek** [malyvoj3/csvw-validator#2]
Cannot install app. When running `mvn clean install` I get:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project csvw-validator: Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags -> [Help 1]
```
Java: 11.0.2
Maven: 3.5.2

Is Java 8 required, or is it a minimal version and the problem is elsewhere?

**Comment by malyvoj3** [comment]
Problem was with Lombok library version, which didn't support newer versions of Java. I updated Lombok version to the latest one, which should already contains support for Java 10/11. Try it now please.
