### ISSUE TITLE
False negative on validation

### ISSUE THREAD

**Issue by jakubklimek** [malyvoj3/csvw-validator#20]
With [this file](http://opendata.iprpraha.cz/CUR/DOP/DOP_Cyklogenerel_l/CIS_kategorie.csv) the validator does not display any warnings. However, the Content-Type header is wrong and the schema (descriptor) is missing.

**Comment by malyvoj3** [comment]
Warnings for this file are displayed if strict mode is enabled. Strict mode should be enabled by default, which is already in issue https://github.com/malyvoj3/csvw-validator/issues/24. So i will close this one.
