### ISSUE TITLE
Wrong button labels on results page

### ISSUE THREAD

**Issue by jakubklimek** [malyvoj3/csvw-validator#22]
It is unclear what "Download CSV" and "Download RDF" means on the results page.
![image](https://user-images.githubusercontent.com/718827/56642504-d60f9e80-6677-11e9-9f8f-0cb18a77c994.png)

It should say "Results in CSV" and "Results in RDF".

**Comment by malyvoj3** [comment]
Fixed in new UI in pull request https://github.com/malyvoj3/csvw-validator/pull/27
