### ISSUE TITLE
When validating larger files, I run into Java Heap Space error

### ISSUE THREAD

**Issue by jakubklimek** [malyvoj3/csvw-validator#25]
It seems that the validator loads the entire CSV file into memory for validation. This is not usable for larger files and on servers providing validation services to multiple users. The received file should be temporarily stored somewhere and validated in a streaming fashion. This way, there should not be any memory problems.

**Comment by malyvoj3** [comment]
The way of parsing files was changed in pull request https://github.com/malyvoj3/csvw-validator/pull/27
