### ISSUE TITLE
What does "unknown property header" mean?

### ISSUE THREAD

**Issue by jakubklimek** [malyvoj3/csvw-validator#28]
When validating [this](https://www.cnb.cz/cs/dohled-financni-trh/.galleries/seznamy/otevrena_data/download/npsu.json) file, I get `Unknown property header` warning. I do not know what it means.
![image](https://user-images.githubusercontent.com/718827/57071627-4ef7a180-6cdb-11e9-9c8c-f68abc87201d.png)

**Comment by malyvoj3** [comment]
Ok i will specify this message. It means that JSON-LD descriptor has object with property, which is not defined by CSV on the Web. Eg. here you have property 'header' in Table or Table group description object.

**Comment by malyvoj3** [comment]
I close this one, it is covered by issue https://github.com/malyvoj3/csvw-validator/issues/34
