### ISSUE TITLE
Web view is wider than necessary - shows scrollbar

### ISSUE THREAD

**Issue by jakubklimek** [malyvoj3/csvw-validator#29]
The page is unnecessarily wide - causing an unnecessary horizontal scroll bar.
![image](https://user-images.githubusercontent.com/718827/57071855-0096d280-6cdc-11e9-84dd-56dce44a5573.png)

**Comment by malyvoj3** [comment]
Fixed in pull request https://github.com/malyvoj3/csvw-validator/pull/39.
