### ISSUE TITLE
Add validation statistics

### ISSUE THREAD

**Issue by jakubklimek** [malyvoj3/csvw-validator#30]
It would be good to show some basic validation statistics about the input files, at least number of rows, number of columns, ideally the number of rows validated OK, number of rows generating warnings and number of rows generating errors.

Even though the validator may work, the issue with the results in the current form is, that for some reason (probably based on my experience with other web tools), I do feel nervous when I see the OK result. I am just not convinced (as a user) that the tool actually went through the file and did not, for instance, validate an empty CSV file for some reason.

**Comment by malyvoj3** [comment]
If validator validates CSV or JSON-LD descriptor, which describes table, then creation of these statistics is obvious. But what if validator validates group of tables? There are multiple tables.

**Comment by jakubklimek** [comment]
OK, I actually did not think about such an advanced case. Do you have test data for that?

Even then, the total number of rows could be displayed, maybe along with the number of tables in the group? (I am just guessing here). The point is to show some convincing indication that the input data was actually processed by the validator.

**Comment by malyvoj3** [comment]
There is eg. CSVW test http://w3c.github.io/csvw/tests/test272-metadata.json.
I think there can be 2 types of this statistic. Just for one table with number of columns, rows,... And for group of table with number of tables and sum of row.

**Comment by malyvoj3** [comment]
For now I added statistics: number of processed tables, total number of processed rows and column.
Implemented in pull request https://github.com/malyvoj3/csvw-validator/pull/39
