### ISSUE TITLE
Make the tabs scroll (or their labels shorter) in mobile view

### ISSUE THREAD

**Issue by jakubklimek** [malyvoj3/csvw-validator#33]
In Mobile view, the tabs in the Validation page are unnecessarily wide. I would shorten their texts for mobile view, or at least make them scrollable, so that they don't make the whole page scroll horizontally.

![image](https://user-images.githubusercontent.com/718827/57072574-7f8d0a80-6cde-11e9-83f2-367c709c92ff.png)

**Comment by malyvoj3** [comment]
Fixed in pull request https://github.com/malyvoj3/csvw-validator/pull/39. Now they are scrollable.
