### ISSUE TITLE
Downloaded files stay in target/tmp forever

### ISSUE THREAD

**Issue by jakubklimek** [malyvoj3/csvw-validator#35]
The files downloaded in a temp folder stay there.
For a publicly accessible service, this will cause the server to run out of disk space. After validation (or when it is cancelled), the files should be deleted.

**Comment by malyvoj3** [comment]
For now they should be deleted when JVM is terminated (Java method `file.deleteOnExit()` and before app startup the folder is deleted. But I agree that deleting after validation will be better solution.

**Comment by malyvoj3** [comment]
Fixed in pull request https://github.com/malyvoj3/csvw-validator/pull/39.
