### ISSUE TITLE
Make the validation result persistent

### ISSUE THREAD

**Issue by jakubklimek** [malyvoj3/csvw-validator#38]
The validation result is not persistent now, which means I cannot share it with anyone.
The result should have its own ID (guid) and it should be persisted, so that based on that ID I am able to construct a URL which I can share with other users.

This ID should also be returned for the Web Service call, so that the third-party web application calling the validator ([such as this one](https://data.gov.cz/datová-sada?iri=https://data.gov.cz/zdroj/datové-sady/http---atom.cuzk.cz-api-3-action-package_show-id-vo)) can display a link leading to the validation results web view.

**Comment by malyvoj3** [comment]
It was implemented in pull request https://github.com/malyvoj3/csvw-validator/pull/39. Now there is /validationResult/{resultId} endpoint, see readme. And web application has /result/{resultId} screen.
