### ISSUE TITLE
Validation hangs

### ISSUE THREAD

**Issue by jakubklimek** [malyvoj3/csvw-validator#40]
Validating [this file](https://mvcr1.opendata.cz/czechpoint/2008.json) currently hangs the validator.

**Comment by malyvoj3** [comment]
I can't reproduce it. It is long validation (about 4 minutes), but it finishes everytime. There is around 980k rows and 7 columns = almost 7M cells, which are validated if the datatype is correct and if primary keys are unique. In the future there can be added some efficient improvements and/or multithreading.

**Comment by jakubklimek** [comment]
You are right, it took a long time, but it finished all right. It would be nice to have some progress indicator better than the "infinite" one - you could report number of rows processed. But this is a low priority issue.
