### ISSUE TITLE
False warning about missing Content-Type

### ISSUE THREAD

**Issue by jakubklimek** [malyvoj3/csvw-validator#7]
When accessing [this file](http://opendata.praha.eu/dataset/cddf7030-c439-4251-a47c-43cb5372b675/resource/dec3e4fb-b624-4f55-80a0-4713d5800481/download/924a36cc-6286-49f8-b8c3-12782823797e-akcezoo.csv), I actually see `Content-Type: text/csv` in the response headers. Nevertheless, I get the `CSV file doesn't have specified 'Content-type' HTTP header.` warning. Maybe the check is case sensitive when it should not be?

**Comment by malyvoj3** [comment]
Problem was with bad header parsing. It was solved in commit cf02da50353e6141c17c4fa024c31f0d8375ff85.
