### ISSUE TITLE
Add example showing how to mass validate CSV files

### ISSUE THREAD

**Issue by jakubklimek** [malyvoj3/csvw-validator#9]
It is [quite simple](https://data.gov.cz/sparql?default-graph-uri=&query=PREFIX+dcat%3A+%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fdcat%23%3E%0D%0A%0D%0ASELECT+%3Furl+WHERE%0D%0A%7B%0D%0A%3Fdistro+a+dcat%3ADistribution%3B%0D%0Adcat%3AdownloadURL+%3Furl+%3B%0D%0Adcat%3AmediaType+%3Chttp%3A%2F%2Fwww.iana.org%2Fassignments%2Fmedia-types%2Ftext%2Fcsv%3E+.%0D%0A+%0D%0A%7D&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+) to get a list of all CSV files registered in the National Open Data Catalog using this query:
```sparql
PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT ?url WHERE
{
?distro a dcat:Distribution;
dcat:downloadURL ?url ;
dcat:mediaType <http://www.iana.org/assignments/media-types/text/csv> .
}
```

Now I should be able to "mass validate" them, creating a separate report for each file and a summary statistic (number of files validated, number of files without errors, number of files without errors and warnings).

Find out the best way of doing this. I suspect a shell script using the API could do it.

**Comment by jakubklimek** [comment]
This is also a good test case btw.

**Comment by malyvoj3** [comment]
Added support for REST API (```/validateBatch``` endpoint) and example script (```batchValidation.sh```) in pull request https://github.com/malyvoj3/csvw-validator/pull/12
